### PR TITLE
Remove socket file if it exists during boot

### LINKED ISSUE #21: Error: can't listen on "/csi/csi.sock" using unix protocol: listen unix /csi/csi.sock: bind: address already in use
## Issue description

One of the CSI driver instances failed to start with the following error:

```
I0623 17:30:37.071240       1 local-csi-driver/driver.go:119] "Driver started" command="local-csi-driver" version="\"v0.1.0-beta.1-0-ga59b0f8\""
I0623 17:30:37.071291       1 flag/flags.go:64] FLAG: --driver-name="local.csi.scylladb.com"
I0623 17:30:37.071298       1 flag/flags.go:64] FLAG: --help="false"
I0623 17:30:37.071303       1 flag/flags.go:64] FLAG: --listen="/csi/csi.sock"
I0623 17:30:37.071306       1 flag/flags.go:64] FLAG: --loglevel="2"
I0623 17:30:37.071310       1 flag/flags.go:64] FLAG: --node-name="ip-10-12-7-103.ec2.internal"
I0623 17:30:37.071314       1 flag/flags.go:64] FLAG: --v="2"
I0623 17:30:37.071317       1 flag/flags.go:64] FLAG: --volumes-dir="/mnt/persistent-volumes"
Error: can't listen on "/csi/csi.sock" using unix protocol: listen unix /csi/csi.sock: bind: address already in use
```

It's liveness probe results:

```
I0623 16:26:34.852622       1 main.go:149] calling CSI driver to discover driver name
I0623 16:26:34.853747       1 main.go:155] CSI driver name: "local.csi.scylladb.com"
I0623 16:26:34.853773       1 main.go:183] ServeMux listening at "0.0.0.0:9809"
W0623 16:46:30.509744       1 connection.go:173] Still connecting to unix:///csi/csi.sock
E0623 16:47:08.559050       1 main.go:64] failed to establish connection to CSI driver: context deadline exceeded
E0623 16:47:15.126560       1 main.go:64] failed to establish connection to CSI driver: context canceled
W0623 16:47:15.345008       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:15.424984       1 connection.go:173] Still connecting to unix:///csi/csi.sock
E0623 16:47:15.430405       1 main.go:64] failed to establish connection to CSI driver: context canceled
E0623 16:47:15.474940       1 main.go:64] failed to establish connection to CSI driver: context canceled
E0623 16:47:15.561968       1 connection.go:132] Lost connection to unix:///csi/csi.sock.
E0623 16:47:15.593518       1 main.go:64] failed to establish connection to CSI driver: context canceled
W0623 16:47:18.054903       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:25.236508       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:25.349541       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:25.500791       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:25.660422       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:30.794906       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:35.503076       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:35.595067       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:35.803256       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:36.158894       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:38.055628       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:50.060415       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:48:25.593549       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:47:53.150225       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:48:07.698577       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:48:22.719607       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:48:24.376925       1 connection.go:173] Still connecting to unix:///csi/csi.sock
E0623 16:48:25.422562       1 main.go:64] failed to establish connection to CSI driver: context canceled
E0623 16:48:25.422706       1 main.go:64] failed to establish connection to CSI driver: context canceled
E0623 16:48:25.423525       1 main.go:64] failed to establish connection to CSI driver: context canceled
E0623 16:48:25.485253       1 main.go:64] failed to establish connection to CSI driver: context canceled
E0623 16:48:25.424495       1 main.go:64] failed to establish connection to CSI driver: context canceled
W0623 16:48:25.714499       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0623 16:48:25.726677       1 connection.go:173] Still connecting to unix:///csi/csi.sock
...
< ~2600 more 'Still connecting to unix:///csi/csi.sock' messages>
...
W0623 17:32:08.055199       1 connection.go:173] Still connecting to unix:///csi/csi.sock
```

## Impact

Breakage of a Scylla member creation

## How frequently does it reproduce?

~5-10%

## Installation details

Kernel Version: 5.10.179-168.710.amzn2.x86_64
Scylla version (or git commit hash): `2022.2.9-20230618.843304f9f734` with build-id `a34753ee38bccbaf461e04ae0e63e17afe45e048`

K8S local-volume-provisioner image: docker.io/scylladb/k8s-local-volume-provisioner:0.1.0-rc.0

Operator Image: scylladb/scylla-operator:1.9.0-rc.1
Operator Helm Version: 1.9.0-rc.1
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 3 nodes (i3.2xlarge)

OS / Image: `` (k8s-eks: undefined_region)

Test: `perf-regression-throughput-eks`
Test id: `657ce2c4-2bbf-4941-8d23-8be7f0a2487d`
Test name: `scylla-operator/operator-1.9/performance/perf-regression-throughput-eks`
Test config file(s):

- [perf-regression.100threads.30M-keys.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/538f20e571a250a3fbbd456f26ddddbedbc6abd1/test-cases/performance/perf-regression.100threads.30M-keys.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 657ce2c4-2bbf-4941-8d23-8be7f0a2487d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=657ce2c4-2bbf-4941-8d23-8be7f0a2487d)
- Show all stored logs command: `$ hydra investigate show-logs 657ce2c4-2bbf-4941-8d23-8be7f0a2487d`

## Logs:
- **db-cluster-657ce2c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/db-cluster-657ce2c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/db-cluster-657ce2c4.tar.gz)
- **sct-runner-events-657ce2c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/sct-runner-events-657ce2c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/sct-runner-events-657ce2c4.tar.gz)
- **sct-657ce2c4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/sct-657ce2c4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/sct-657ce2c4.log.tar.gz)
- **monitor-set-657ce2c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/monitor-set-657ce2c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/monitor-set-657ce2c4.tar.gz)
- **loader-set-657ce2c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/loader-set-657ce2c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/loader-set-657ce2c4.tar.gz)
- **kubernetes-657ce2c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/kubernetes-657ce2c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/657ce2c4-2bbf-4941-8d23-8be7f0a2487d/20230623_174133/kubernetes-657ce2c4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.9/job/performance/job/perf-regression-throughput-eks/8/)
[Argus](https://argus.scylladb.com/test/e8c0209f-72d9-48d0-bd13-a45fa9e23e34/runs?additionalRuns[]=657ce2c4-2bbf-4941-8d23-8be7f0a2487d)
</details>

### PR DESCRIPTION
**Pull request by zimnx**
Socket file may exist when node terminates ungracefuly. Existance of it prevented driver from booting. To overcome this, we remove it before we start listening.

Tested on VM where I was able to reproduce it 100% times when VM was powered off. Issue is no longer present with the fix.

Fixes #21

### CODE REVIEW

File: pkg/cmd/local-csi-driver/driver.go [hunk 1]
```diff
@@ -159,6 +159,10 @@ func (o *LocalDriverOptions) run(ctx context.Context, _ genericclioptions.IOStre
 		return fmt.Errorf("can't create driver: %w", err)
 	}
 
+	if err := os.Remove(o.Listen); err != nil && !os.IsNotExist(err) {
```
Comment (tnozicka) [inline pkg/cmd/local-csi-driver/driver.go:162]: what if it is actually still running? (DS doesn't guarantee single pod + rolling update is desired)

Comment (zimnx) [reply pkg/cmd/local-csi-driver/driver.go:162]: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy
>  At most one pod of the DaemonSet will be running on each node during the whole update process.

Socket file is removed on graceful shutdown.

Comment (tnozicka) [reply pkg/cmd/local-csi-driver/driver.go:162]: That's a fairly hard statement in  an eventually consistent system without using pod name as an identity. Putting that aside we should use MaxSurge for HA eventually 
```
$ kubectl explain daemonsets.apps/v1.spec.updateStrategy.rollingUpdate.maxSurge
KIND:     DaemonSet
VERSION:  apps/v1

FIELD:    maxSurge <string>

DESCRIPTION:
     The maximum number of nodes with an existing available DaemonSet pod that
     can have an updated DaemonSet pod during during an update. Value can be an
     absolute number (ex: 5) or a percentage of desired pods (ex: 10%). This can
     not be 0 if MaxUnavailable is 0. Absolute number is calculated from
     percentage by rounding up to a minimum of 1. Default value is 0. Example:
     when this is set to 30%, at most 30% of the total number of nodes that
     should be running the daemon pod (i.e. status.desiredNumberScheduled) can
     have their a new pod created before the old pod is marked as deleted. The
     update starts by launching new pods on 30% of nodes. Once an updated pod is
     available (Ready for at least minReadySeconds) the old DaemonSet pod on
     that node is marked deleted. If the old pod becomes unavailable for any
     reason (Ready transitions to false, is evicted, or is drained) an updated
     pod is immediatedly created on that node without considering surge limits.
     Allowing surge implies the possibility that the resources consumed by the
     daemonset on any given node can double if the readiness check fails, and so
     resource intensive daemonsets should take into account that they may cause
     evictions during disruption.

     IntOrString is a type that can hold an int32 or a string. When used in JSON
     or YAML marshalling and unmarshalling, it produces or consumes the inner
     type. This allows you to have, for example, a JSON field that can accept a
     name or number.
```

Comment (rzetelskik) [reply pkg/cmd/local-csi-driver/driver.go:162]: Not sure if we should care about it, but what happens if you accidentally deploy two instances of the service on the same node? Are they just going to delete the socket in a loop?

Comment (tnozicka) [reply pkg/cmd/local-csi-driver/driver.go:162]: https://github.com/scylladb/k8s-local-volume-provisioner/issues/25

**Review by tnozicka — APPROVED** [review]
/lgtm
let's have a starting point,we can defer something more complex when we look into #25
